name: Release Charts

on:
  workflow_run:
    workflows: ["Lint and Test Charts"]
    branches: [main]
    types: 
      - completed

permissions: read-all 

jobs:
  release:
    permissions: 
      packages: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        
      - name: add repo dependencies
        run: |
          helm repo add https://charts.bitnami.com/bitnami
        
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
